
all: shared_ptr unique_ptr

clean:
	rm  shared_ptr unique_ptr
shared_ptr: shared_ptr.cpp
	clang++ shared_ptr.cpp -std=c++14 -o shared_ptr
unique_ptr: unique_ptr.cpp
	clang++ unique_ptr.cpp -std=c++14 -o unique_ptr
