
all: constants constexpr ifinitial initializer_list structured_binding auto decltype

constants: constants.cpp
	clang++ constants.cpp -std=c++14 -o constants
constexpr: constexpr.cpp
	clang++ constexpr.cpp -std=c++14 -o constexpr
ifinitial: if_initial.cpp
	clang++ if_initial.cpp -std=c++14 -o ifinitial
initializer_list: initializer_list.cpp
	clang++ initializer_list.cpp -std=c++14 -o initializer_list
structured_binding: structured_binding.cpp
	clang++ structured_binding.cpp -std=c++14 -o structured_binding
auto: auto.cpp
	clang++ auto.cpp -std=c++14 -o auto
decltype: decltype.cpp
	clang++ decltype.cpp -std=c++14 -o decltype

